coverage:
  precision: 2
  round: up
  # trunk-ignore(yamllint/quoted-strings)
  range: "95...100"
  status:
    patch:
      default:
        target: 95%
    project:
      default:
        target: 95%
