"""init

Revision ID: ae0d46c8c57a
Revises: 
Create Date: 2023-09-06 05:56:00.027745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0d46c8c57a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_created_at'), 'story', ['created_at'], unique=False)
    op.create_index(op.f('ix_story_id'), 'story', ['id'], unique=False)
    op.create_index(op.f('ix_story_updated_at'), 'story', ['updated_at'], unique=False)
    op.create_table('bug',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_created_at'), 'bug', ['created_at'], unique=False)
    op.create_index(op.f('ix_bug_id'), 'bug', ['id'], unique=False)
    op.create_index(op.f('ix_bug_updated_at'), 'bug', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bug_updated_at'), table_name='bug')
    op.drop_index(op.f('ix_bug_id'), table_name='bug')
    op.drop_index(op.f('ix_bug_created_at'), table_name='bug')
    op.drop_table('bug')
    op.drop_index(op.f('ix_story_updated_at'), table_name='story')
    op.drop_index(op.f('ix_story_id'), table_name='story')
    op.drop_index(op.f('ix_story_created_at'), table_name='story')
    op.drop_table('story')
    # ### end Alembic commands ###
