"""third revision

Revision ID: c0eda1b072d3
Revises: d843b9dcec2a
Create Date: 2023-09-01 04:38:11.799298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0eda1b072d3'
down_revision: Union[str, None] = 'd843b9dcec2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bug_created_at', table_name='bug')
    op.drop_index('ix_story_created_at', table_name='story')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_story_created_at', 'story', ['created_at'], unique=False)
    op.create_index('ix_bug_created_at', 'bug', ['created_at'], unique=False)
    # ### end Alembic commands ###
